
name: riyobox
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  provider: ^6.1.5+1
  go_router: ^14.2.0
  transparent_image: ^2.0.1
  video_player: ^2.10.1
  screen_brightness: ^2.1.7
  wakelock_plus: ^1.4.0
  flutter_volume_controller: ^1.3.4
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  dio: ^5.4.1
  file_picker: ^8.0.3
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  flutter_chrome_cast: 1.3.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
